version: "3"

services:
  php:
    container_name: "ci_code_tests_php"
    image: wodby/php:8.1
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html:cached
  nginx:
    container_name: "ci_code_tests_nginx"
    image: wodby/nginx:1.23-5.27.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public/
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/html:cached
