name: PHP Code full tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  magic-numbers-test-small:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Run Magic numbers test (full)
      run: composer run phpmnd-full

  magic-numbers-test-default:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Run Magic numbers test (full)
      run: composer run phpmnd

  magic-numbers-test-full:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Run Magic numbers test (full)
      run: composer run phpmnd-full

  phpmd:

    name: PHPMD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run PHPMD
        run: phpmd . github ../rulesets/phpmd.ruleset.xml --exclude 'tests/*,vendor/*'

